export const ASSETS = {
  imgActivity: "/icons/activity-outline.svg",
  imgActivityBold: "/icons/activity-bold.svg",
  imgCube: "/icons/cube.svg",
  imgProduct: "/icons/products-outline.svg",
  imgProductBold: "/icons/product-bold.svg",
  imgNotification: "/icons/notification.svg",
  imgProfile: "/icons/profile.svg",
  imgArrowDown: "/icons/arrow-down.svg",
  imgLogo: "/icons/icon/dio-logo.svg",
  imgProductsEmpty: "/icons/products-empty.svg",
  imgAddCircle: "/icons/add-circle.svg",
  imgClose: "/icons/close.svg",
  imgBoxAdd: "/icons/box-add.svg",
  imgArrowLeft: "/icons/arrow-left.svg",
  imgChevronLeft: "/icons/chevron/left.svg",
  imgMore: "/icons/more.svg",
  imgCubeScan: "/icons/cube.svg",
  imgEdit: "/icons/edit.svg",
  imgTrash: "/icons/trash.svg",
  // New Assets
  imgIconLock: "/icons/icon-lock.svg",
  imgInfoCircle: "/icons/info-circle.svg",
  imgCopy: "/icons/copy.svg",
  imgSettings: "/icons/settings.svg",
  imgMouseSquare: "/icons/mouse-square.svg",
  imgHeatmap: "/icons/heatmap.svg",
  imgSocial: "/icons/social.svg",
  imgBazar: "/icons/bazar.svg",
  imgCalendar: "/icons/calendar.svg",
  imgRefresh: "/icons/refresh.svg",
  imgSupport: "/icons/support.svg",
  imgRecording: "/icons/recording.svg",
  imgPlay: "/icons/icon/play.svg",
  imgBazarOwner: "/icons/bazar-owner.svg",
};
